name: flutter_firebase
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  math_expressions: ^2.0.0
  font_awesome_flutter: ^10.1.0
  provider: ^6.1.2
  firebase_core: ^3.2.0 
  firebase_auth: ^5.1.2 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/home_background.jpg
    - assets/images/login.jpg
    - assets/images/signup.jpg
    - assets/images/forgot_pw.jpg

