// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFVbgP3LXKXVjM08uVUMC4ZTSzxuPqJRg',
    appId: '1:21756736827:web:0d4127b4d22b28427c331e',
    messagingSenderId: '21756736827',
    projectId: 'testing-cli-1653',
    authDomain: 'testing-cli-1653.firebaseapp.com',
    storageBucket: 'testing-cli-1653.appspot.com',
    measurementId: 'G-TY6RFX76YH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALJwBmP_Npmbz5PyKF3HoLgtAawfF5XSc',
    appId: '1:21756736827:android:2862c63a943920b47c331e',
    messagingSenderId: '21756736827',
    projectId: 'testing-cli-1653',
    storageBucket: 'testing-cli-1653.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUkjPNsqIS7wyuoh2q5TLVN3hCe6CkhW8',
    appId: '1:21756736827:ios:0913afadfcbbcb1c7c331e',
    messagingSenderId: '21756736827',
    projectId: 'testing-cli-1653',
    storageBucket: 'testing-cli-1653.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
